# Use an official Node.js image as the build environment
FROM node:20.11.0

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app
COPY . ./

# Running server Port
EXPOSE 3000

# Build the app
RUN npm run build

# Run the Frontend Folder
CMD ["npm", "start"]


